# file: calibration_config.yaml
general:
  strategy:
      # Type of strategy, currently supported is estimation
      type: estimation
      # defaults to dds (currently, the only supported algorithm)
      algorithm: "dds"

  # Enable model runtime logging (captures standard out and error and writes to file)
  # logs will be written to <model.type>.log when enabled
  # defaults to False, which sends all output to /dev/null
  log: True

  start_iteration: 0
  # The total number of search iterations to run
  iterations: 100
  random_seed: 444
  workdir: ./
  plugins:
     - "ngen_cal_user_plugins.ngen_cal_save_iteration_output_plugin.SaveValidation"  # saves ngen *.csv to "output_validation" directory
     - "ngen_cal_user_plugins.ngen_cal_read_obs_plugin.ReadObservedData"

# Define parameters to calibrate, their bounds, and initial values.
lgar_params: &lgar_params
  - name: smcmin
    init: 0.08
    min: 0.01
    max: 0.15
  - name: smcmax
    init: 0.439
    min: 0.2
    max: 0.6
  - name: van_genuchten_n
    init: 2.0
    min: 1.01
    max: 3.0
  - name: van_genuchten_alpha
    init: 0.1
    min: 0.001
    max: 0.3
  - name: hydraulic_conductivity
    init: 0.5
    min: 0.001
    max: 100
  - name: field_capacity
    init: 340.9
    min: 10.3
    max: 516.6
  - name: ponded_depth_max
    init: 0.01
    min: 0.0
    max: 2.0


# Model specific configuration
model:
    type: ngen
    # NOTE: you may need to adjust this to the location of your NextGen installation
    # A binary in $PATH or a qualified path to the binary to run
    binary: "./ngen/cmake_build/ngen"
    realization: ./realization.json
    # Required path to catchment hydrofabirc file
    hydrofabric: ./Gage_1022500.gpkg
    eval_feature: wb-3550
    # Each catchment upstream of observable nexus gets its own permuted parameter space, evaluates at one observable nexus 
    strategy: uniform
    params:
        # Note, this name MUST be the same as the realization model_type_name for the keys
        LGAR: *lgar_params

    eval_params:
      # choices are "kling_gupta", "nnse", "custom", "single_peak", "volume"
      objective: "kling_gupta"
    plugins:
      - "ngen_cal_user_plugins.ngen_cal_save_iteration_output_plugin.SaveCalibration" # saves ngen *.csv to "output_iteration" directory
      - "ngen_cal_user_plugins.ngen_cal_save_sim_obs_plugin.SaveOutput"               # saves simulated and observed discharge at the outlet
      - "ngen_cal_user_plugins.ngen_cal_read_obs_plugin.ReadObservedData"
      #- "ngen_cal_user_plugins.ngen_cal_symlink_plugin.NgenCalSymlinkDir"
    plugin_settings:
      ngen_cal_read_obs_data:
        obs_data_path: /home/ec2-user/core/tnc-dangermond/simulations/stream_discharge-19791001-19820929_11120600.csv
        units: "ft3/sec"
        window: 24 # data interval in hours
      #ngen_cal_symlink_dir:
      #  path: "./outputs_calib"
